import type { Metadata } from "next";
import { Commissioner } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const commissioner = Commissioner({});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        id="root"
        className={`${commissioner.className} bg-surface-600 text-fg min-h-dvh`}
      >
        {children}
      </body>
    </html>
  );
}
